package com.audioly.app.extraction

import com.audioly.app.util.UrlValidator
import org.junit.Assert.*
import org.junit.Test

class YouTubeExtractorTest {

    // --- ExtractionResult model tests (no network) ---

    @Test fun `InvalidUrl is returned for non-youtube url`() {
        val result = ExtractionResult.Failure.InvalidUrl("https://vimeo.com/123")
        assertTrue(result is ExtractionResult.Failure.InvalidUrl)
        assertEquals("https://vimeo.com/123", (result as ExtractionResult.Failure.InvalidUrl).url)
    }

    @Test fun `Success wraps StreamInfo correctly`() {
        val info = StreamInfo(
            videoId = "abc123",
            title = "Test Video",
            uploader = "Test Channel",
            thumbnailUrl = "https://img.youtube.com/vi/abc123/maxresdefault.jpg",
            durationSeconds = 300L,
            audioStreamUrl = "https://audio.example.com/stream.mp4",
            subtitleTracks = emptyList()
        )
        val result = ExtractionResult.Success(info)
        assertEquals("abc123", result.streamInfo.videoId)
        assertEquals("Test Video", result.streamInfo.title)
        assertEquals(300L, result.streamInfo.durationSeconds)
    }

    @Test fun `SubtitleTrack ordering manual before auto`() {
        val manual = SubtitleTrack("en", "English", false, "url1", "vtt")
        val auto = SubtitleTrack("en", "English", true, "url2", "vtt")
        val tracks = listOf(auto, manual)
        val sorted = tracks.sortedWith(
            compareBy<SubtitleTrack> { if (it.isAutoGenerated) 1 else 0 }
                .thenBy { it.languageCode }
        )
        assertFalse(sorted[0].isAutoGenerated) // manual first
        assertTrue(sorted[1].isAutoGenerated)
    }

    @Test fun `SubtitleTrack ordering alphabetical within group`() {
        val t1 = SubtitleTrack("zh", "Chinese", false, "u1", "vtt")
        val t2 = SubtitleTrack("ar", "Arabic", false, "u2", "vtt")
        val t3 = SubtitleTrack("en", "English", false, "u3", "vtt")
        val sorted = listOf(t1, t2, t3).sortedBy { it.languageCode }
        assertEquals("ar", sorted[0].languageCode)
        assertEquals("en", sorted[1].languageCode)
        assertEquals("zh", sorted[2].languageCode)
    }

    @Test fun `UrlValidator integration - invalid url produces no videoId`() {
        assertNull(UrlValidator.extractVideoId("https://vimeo.com/watch?v=abc"))
    }

    @Test fun `UrlValidator integration - valid url produces videoId`() {
        assertEquals("dQw4w9WgXcQ", UrlValidator.extractVideoId("https://youtu.be/dQw4w9WgXcQ"))
    }

    @Test fun `StreamInfo holds subtitle tracks`() {
        val subs = listOf(
            SubtitleTrack("en", "English", false, "url", "vtt"),
            SubtitleTrack("ar", "Arabic", true, "url2", "vtt")
        )
        val info = StreamInfo("vid", "Title", "Channel", "", 100L, "streamUrl", subs)
        assertEquals(2, info.subtitleTracks.size)
        assertEquals("en", info.subtitleTracks[0].languageCode)
    }
}
