package com.audioly.app.data.db.entities

import androidx.room.Entity
import androidx.room.ForeignKey
import androidx.room.Index

/**
 * Cached subtitle file record.
 * [filePath] is the on-disk path relative to the app cache directory.
 * [languageCode] is a BCP-47 tag (e.g. "en", "ar", "zh-Hans").
 */
@Entity(
    tableName = "subtitle_cache",
    primaryKeys = ["videoId", "languageCode"],
    foreignKeys = [
        ForeignKey(
            entity = TrackEntity::class,
            parentColumns = ["videoId"],
            childColumns = ["videoId"],
            onDelete = ForeignKey.CASCADE,
        ),
    ],
    indices = [Index("videoId")],
)
data class SubtitleCacheEntity(
    val videoId: String,
    val languageCode: String,
    val languageName: String,
    val filePath: String,
    /** "vtt" or "srt" */
    val format: String,
    val isAutoGenerated: Boolean,
    val cachedAt: Long = System.currentTimeMillis(),
)
