package com.audioly.app.data.cache

import com.audioly.app.data.db.dao.SubtitleCacheDao
import com.audioly.app.data.db.entities.SubtitleCacheEntity
import java.io.File

/**
 * Manages subtitle files on disk under `<cacheDir>/subtitles/<videoId>/<languageCode>.<format>`.
 * Room rows are kept in sync via [SubtitleCacheDao].
 */
class SubtitleCacheManager(
    private val subtitleRootDir: File,
    private val dao: SubtitleCacheDao,
) {

    init {
        subtitleRootDir.mkdirs()
    }

    // ─── Write ────────────────────────────────────────────────────────────────

    /**
     * Persist [content] to disk and record in Room.
     * @return absolute path of the written file.
     */
    suspend fun save(
        videoId: String,
        languageCode: String,
        languageName: String,
        format: String,
        isAutoGenerated: Boolean,
        content: String,
    ): String {
        val dir = File(subtitleRootDir, videoId).also { it.mkdirs() }
        val file = File(dir, "$languageCode.$format")
        // Atomic write: write to temp file then rename to prevent corrupt files on crash
        val tempFile = File(dir, "$languageCode.$format.tmp")
        try {
            tempFile.writeText(content)
            if (!tempFile.renameTo(file)) {
                // renameTo can fail on some filesystems; fall back to copy + delete
                tempFile.copyTo(file, overwrite = true)
                tempFile.delete()
            }
        } catch (e: Exception) {
            // Clean up temp file on failure
            tempFile.delete()
            throw e
        }
        dao.upsert(
            SubtitleCacheEntity(
                videoId = videoId,
                languageCode = languageCode,
                languageName = languageName,
                filePath = file.absolutePath,
                format = format,
                isAutoGenerated = isAutoGenerated,
            ),
        )
        return file.absolutePath
    }

    // ─── Read ─────────────────────────────────────────────────────────────────

    /** @return file content or null if not cached or unreadable. */
    suspend fun load(videoId: String, languageCode: String): String? {
        val entity = dao.get(videoId, languageCode) ?: return null
        val file = File(entity.filePath)
        if (!file.exists()) {
            // File was deleted (OS cache eviction, manual clear) but DB row remains.
            // Clean up the stale DB entry so it doesn't mislead future lookups.
            dao.delete(videoId, languageCode)
            return null
        }
        return try {
            file.readText().takeIf { it.isNotBlank() }
        } catch (_: Exception) {
            // Corrupted or unreadable file — remove stale entry
            dao.delete(videoId, languageCode)
            null
        }
    }

    suspend fun getCacheEntry(videoId: String, languageCode: String): SubtitleCacheEntity? =
        dao.get(videoId, languageCode)

    suspend fun getAllForVideo(videoId: String): List<SubtitleCacheEntity> =
        dao.getAllForVideo(videoId)

    // ─── Delete ───────────────────────────────────────────────────────────────

    /** Delete a single subtitle track from disk and Room. */
    suspend fun delete(videoId: String, languageCode: String) {
        val entity = dao.get(videoId, languageCode) ?: return
        File(entity.filePath).delete()
        dao.delete(videoId, languageCode)
    }

    /** Delete all subtitle files for a video and their Room rows. */
    suspend fun deleteAllForVideo(videoId: String) {
        val entries = dao.getAllForVideo(videoId)
        entries.forEach { File(it.filePath).delete() }
        File(subtitleRootDir, videoId).deleteRecursively()
        dao.deleteAllForVideo(videoId)
    }

    /** Stable path calculation — usable to check existence without DB lookup. */
    fun pathFor(videoId: String, languageCode: String, format: String): String =
        File(File(subtitleRootDir, videoId), "$languageCode.$format").absolutePath
}
