package com.audioly.app.extraction

import com.audioly.app.util.AppLogger
import org.json.JSONObject
import org.schabi.newpipe.extractor.stream.StreamInfo as NewPipeStreamInfo

object SubtitleExtractor {

    private const val TAG = "SubtitleExtractor"
    private val PREFERRED_FORMATS = listOf("vtt", "ttml", "srv3", "srv2", "srv1", "transcript3")

    /**
     * Extracts subtitle tracks from NewPipe StreamInfo.
     * Manual subtitles before auto-generated; within each group sorted by language code.
     */
    fun extract(npStreamInfo: NewPipeStreamInfo): List<SubtitleTrack> {
        val manual = mutableListOf<SubtitleTrack>()
        val auto = mutableListOf<SubtitleTrack>()

        npStreamInfo.subtitles.forEach { sub ->
            try {
                val langTag = sub.languageTag?.lowercase() ?: "und"
                // displayLanguageName may not exist in all versions; fall back safely
                val langName = try {
                    sub.displayLanguageName.ifBlank { langTag }
                } catch (_: Throwable) {
                    langTag
                }
                // sub.content comes from Java and can be null despite Kotlin type
                val rawUrl = sub.content
                if (rawUrl.isNullOrBlank()) {
                    AppLogger.w(TAG, "Skipping subtitle with null/blank URL: lang=$langTag")
                    return@forEach
                }
                // Always rewrite URL to request VTT format — NewPipe may return
                // srv3/ttml URLs which VttParser cannot parse
                val url = ensureVttFormat(rawUrl)
                val track = SubtitleTrack(
                    languageCode = langTag,
                    languageName = langName,
                    isAutoGenerated = sub.isAutoGenerated,
                    url = url,
                    format = "vtt"
                )
                if (sub.isAutoGenerated) auto.add(track) else manual.add(track)
            } catch (e: Exception) {
                // Skip malformed subtitle entries rather than crashing
                AppLogger.w(TAG, "Skipping malformed subtitle entry: ${e.message}")
            }
        }

        return sortAndDeduplicate(manual, auto).let { addAutoTranslatedEnglish(it) }
    }

    /**
     * Extracts subtitle tracks from InnerTube /player JSON response.
     * Parses captions.playerCaptionsTracklistRenderer.captionTracks array.
     *
     * Each track's URL is rewritten to request VTT format for ExoPlayer compatibility.
     */
    fun extractFromInnerTubeJson(playerResponse: JSONObject): List<SubtitleTrack> {
        val captionTracks = playerResponse
            .optJSONObject("captions")
            ?.optJSONObject("playerCaptionsTracklistRenderer")
            ?.optJSONArray("captionTracks")
            ?: return emptyList()

        val manual = mutableListOf<SubtitleTrack>()
        val auto = mutableListOf<SubtitleTrack>()

        for (i in 0 until captionTracks.length()) {
            val track = captionTracks.optJSONObject(i) ?: continue
            val baseUrl = track.optString("baseUrl", "")
            if (baseUrl.isBlank()) continue

            val languageCode = track.optString("languageCode", "und").lowercase()
            val name = track.optJSONObject("name")?.optString("simpleText", "")
                ?: track.optString("name", "")
            val kind = track.optString("kind", "")
            val isAutoGenerated = kind == "asr"

            // Ensure VTT format in URL
            val vttUrl = ensureVttFormat(baseUrl)

            val subtitleTrack = SubtitleTrack(
                languageCode = languageCode,
                languageName = name.ifBlank { languageCode },
                isAutoGenerated = isAutoGenerated,
                url = vttUrl,
                format = "vtt",
            )
            if (isAutoGenerated) auto.add(subtitleTrack) else manual.add(subtitleTrack)
        }

        return sortAndDeduplicate(manual, auto).let { addAutoTranslatedEnglish(it) }
    }

    // ── Helpers ───────────────────────────────────────────────────────────────

    private fun sortAndDeduplicate(
        manual: List<SubtitleTrack>,
        auto: List<SubtitleTrack>,
    ): List<SubtitleTrack> {
        val sortFn: Comparator<SubtitleTrack> = compareBy(
            { PREFERRED_FORMATS.indexOf(it.format).let { i -> if (i == -1) 999 else i } },
            { it.languageCode }
        )
        return (manual.sortedWith(sortFn) + auto.sortedWith(sortFn))
            .distinctBy { "${it.languageCode}|${it.isAutoGenerated}" }
    }

    private fun ensureVttFormat(baseUrl: String): String {
        if (baseUrl.contains("fmt=vtt")) return baseUrl
        return if (baseUrl.contains("fmt=")) {
            baseUrl.replace(Regex("fmt=[^&]*"), "fmt=vtt")
        } else if (baseUrl.contains("?")) {
            "$baseUrl&fmt=vtt"
        } else {
            "$baseUrl?fmt=vtt"
        }
    }

    /**
     * If no English track exists, creates an auto-translated English track.
     *
     * Primary approach: YouTube timedtext API with `&fmt=json3&tlang=en`.
     * Fallback (handled by PlayerViewModel): download source VTT, translate
     * client-side via Google Translate — uses [sourceLanguageCode] to know
     * which language to translate from and [source.url] to get the VTT.
     */
    private fun addAutoTranslatedEnglish(tracks: List<SubtitleTrack>): List<SubtitleTrack> {
        if (tracks.isEmpty()) return tracks
        val hasEnglish = tracks.any { it.languageCode.startsWith("en") }
        if (hasEnglish) return tracks

        // Prefer ASR (auto-generated) track as translation source — usually the
        // original-language transcript which yields better translations
        val source = tracks.firstOrNull { it.isAutoGenerated } ?: tracks.first()

        // Primary URL: json3 format with &tlang=en for YouTube server-side translation
        val json3Url = ensureFormat(source.url, "json3")
        val translatedUrl = appendOrReplaceParam(json3Url, "tlang", "en")

        val translatedTrack = SubtitleTrack(
            languageCode = "en",
            languageName = "English (Auto-translated)",
            isAutoGenerated = true,
            isAutoTranslated = true,
            url = translatedUrl,
            format = "json3",
            sourceLanguageCode = source.languageCode,
        )
        AppLogger.d(TAG, "Added auto-translated English track (json3) from source lang=${source.languageCode}")
        return tracks + translatedTrack
    }

    /** Sets the `fmt` parameter to the given [format], adding or replacing as needed. */
    private fun ensureFormat(url: String, format: String): String {
        return if (url.contains("fmt=")) {
            url.replace(Regex("fmt=[^&]*"), "fmt=$format")
        } else if (url.contains("?")) {
            "$url&fmt=$format"
        } else {
            "$url?fmt=$format"
        }
    }

    /** Adds or replaces a query parameter in the URL. */
    private fun appendOrReplaceParam(url: String, key: String, value: String): String {
        return if (url.contains("$key=")) {
            url.replace(Regex("$key=[^&]*"), "$key=$value")
        } else if (url.contains("?")) {
            "$url&$key=$value"
        } else {
            "$url?$key=$value"
        }
    }
}
