package com.audioly.app.extraction

import org.schabi.newpipe.extractor.stream.StreamInfo as NewPipeStreamInfo

object SubtitleExtractor {

    private val PREFERRED_FORMATS = listOf("vtt", "ttml", "srv3", "srv2", "srv1", "transcript3")

    /**
     * Extracts subtitle tracks from NewPipe StreamInfo.
     * Manual subtitles before auto-generated; within each group sorted by language code.
     */
    fun extract(npStreamInfo: NewPipeStreamInfo): List<SubtitleTrack> {
        val manual = mutableListOf<SubtitleTrack>()
        val auto = mutableListOf<SubtitleTrack>()

        npStreamInfo.subtitles.forEach { sub ->
            // getFormat() returns MediaFormat from base Stream class; suffix is a public field
            val format = sub.format?.suffix ?: sub.getExtension()
            val langTag = sub.languageTag?.lowercase() ?: "und"
            val track = SubtitleTrack(
                languageCode = langTag,
                languageName = sub.displayLanguageName.ifBlank { langTag },
                isAutoGenerated = sub.isAutoGenerated,
                url = sub.content,
                format = format ?: "vtt"
            )
            if (sub.isAutoGenerated) auto.add(track) else manual.add(track)
        }

        val sortFn: Comparator<SubtitleTrack> = compareBy(
            { PREFERRED_FORMATS.indexOf(it.format).let { i -> if (i == -1) 999 else i } },
            { it.languageCode }
        )

        return (manual.sortedWith(sortFn) + auto.sortedWith(sortFn))
            .distinctBy { it.languageCode + it.isAutoGenerated }
    }
}
