package com.audioly.app.extraction

data class SubtitleTrack(
    val languageCode: String,       // e.g. "en", "ar"
    val languageName: String,       // e.g. "English", "Arabic"
    val isAutoGenerated: Boolean,
    val url: String,
    val format: String,             // e.g. "vtt", "srv3", "json3"
    val isAutoTranslated: Boolean = false,
    /** For auto-translated tracks: the language code of the source track. */
    val sourceLanguageCode: String? = null,
)
