package com.audioly.app.data.repository

import com.audioly.app.data.cache.AudioCacheManager
import com.audioly.app.data.cache.AudioCacheStatus
import com.audioly.app.data.cache.SubtitleCacheManager
import com.audioly.app.data.db.entities.SubtitleCacheEntity
import kotlinx.coroutines.flow.StateFlow

/**
 * Facade over [AudioCacheManager] and [SubtitleCacheManager].
 * Used by the player and library screens to read/evict cache.
 */
class CacheRepository(
    private val audioCacheManager: AudioCacheManager,
    private val subtitleCacheManager: SubtitleCacheManager,
    private val trackRepository: TrackRepository,
) {

    val audioUsedBytes: Long get() = audioCacheManager.usedBytes
    val cacheVersion: StateFlow<Long> get() = audioCacheManager.cacheVersion

    // ─── Audio ────────────────────────────────────────────────────────────────

    fun deleteAudioForVideo(videoId: String) {
        audioCacheManager.deleteForVideo(videoId)
    }

    fun clearAllAudio() = audioCacheManager.clearAll()

    fun getAudioStatus(videoId: String): AudioCacheStatus =
        audioCacheManager.getStatus(videoId)

    fun hasCachedAudio(videoId: String): Boolean =
        audioCacheManager.getStatus(videoId).hasCache

    // ─── Subtitles ────────────────────────────────────────────────────────────

    suspend fun saveSubtitle(
        videoId: String,
        languageCode: String,
        languageName: String,
        format: String,
        isAutoGenerated: Boolean,
        content: String,
    ): String = subtitleCacheManager.save(videoId, languageCode, languageName, format, isAutoGenerated, content)

    suspend fun loadSubtitle(videoId: String, languageCode: String): String? =
        subtitleCacheManager.load(videoId, languageCode)

    suspend fun getSubtitleEntry(videoId: String, languageCode: String): SubtitleCacheEntity? =
        subtitleCacheManager.getCacheEntry(videoId, languageCode)

    suspend fun getCachedSubtitleLanguages(videoId: String): List<SubtitleCacheEntity> =
        subtitleCacheManager.getAllForVideo(videoId)

    // ─── Full eviction ────────────────────────────────────────────────────────

    /** Remove audio + subtitles for a video and clear the audioFilePath in Room. */
    suspend fun deleteVideo(videoId: String) {
        audioCacheManager.deleteForVideo(videoId)
        subtitleCacheManager.deleteAllForVideo(videoId)
        trackRepository.setAudioFilePath(videoId, null)
    }
}
